import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8FAFC" },
  safeArea: { flex: 1 },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 40 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
  },
  title: { fontSize: 20, fontWeight: "700", color: "#0F172A" },

  sessionMetaCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  tripTitle: { fontSize: 17, fontWeight: "800", color: "#0F172A" },
  tripDestination: { marginTop: 2, fontSize: 13, color: "#475569", marginBottom: 6 },
  sessionMetaTitle: { fontSize: 15, fontWeight: "700", color: "#111827" },
  sessionMetaSub: { marginTop: 4, fontSize: 12, color: "#64748B" },
  sessionMetaStatus: { marginTop: 4, fontSize: 12, fontWeight: "600", color: "#334155" },

  actionsRow: { flexDirection: "row", gap: 8, marginBottom: 10 },
  actionBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  actionBtnPrimary: {
    borderColor: "#1D4ED8",
    backgroundColor: "#EFF6FF",
  },
  actionBtnDanger: {
    borderColor: "#FCA5A5",
    backgroundColor: "#FEF2F2",
  },
  actionBtnText: { fontSize: 12, fontWeight: "700", color: "#374151" },
  actionBtnDisabled: { opacity: 0.45 },

  inviteButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  inviteButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
  inlineErrorBanner: {
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inlineErrorText: {
    color: "#991B1B",
    fontSize: 12,
    fontWeight: "600",
  },

  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 8,
  },

  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  summaryInput: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 13,
    color: "#111827",
    backgroundColor: "#FFFFFF",
    marginBottom: 8,
  },
  summaryInputMultiline: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  saveButton: {
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 13 },

  checklistCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  checklistRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  checklistToggle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  checklistToggleActive: {
    backgroundColor: "#22C55E",
    borderColor: "#22C55E",
  },
  checklistToggleText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 12,
  },
  checklistInput: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    paddingHorizontal: 10,
    fontSize: 13,
    color: "#111827",
    backgroundColor: "#FFFFFF",
  },
  checklistInputDone: {
    textDecorationLine: "line-through",
    color: "#6B7280",
  },
  removeChecklistButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FECACA",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF1F2",
  },
  addChecklistRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  newChecklistInput: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    paddingHorizontal: 10,
    fontSize: 13,
    color: "#111827",
    backgroundColor: "#FFFFFF",
  },
  addChecklistButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2563EB",
  },

  notificationConfigCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  pdfSection: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  pdfHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  pdfUploadButton: {
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: "#1E1E1E",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  pdfUploadButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  pdfCard: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    backgroundColor: "#FFFFFF",
  },
  pdfMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pdfMetaTextWrap: {
    flex: 1,
  },
  pdfTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1F2937",
  },
  pdfSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: "#6B7280",
  },
  pdfActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  pdfDownloadButton: {
    flex: 1,
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  pdfDownloadText: {
    color: "#1F2937",
    fontSize: 12,
    fontWeight: "700",
  },
  pdfDeleteButton: {
    minHeight: 36,
    borderRadius: 10,
    paddingHorizontal: 10,
    backgroundColor: "#B91C1C",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  pdfDeleteText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  switchRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#E5E7EB",
    paddingVertical: 6,
  },
  switchLabel: {
    flex: 1,
    marginRight: 8,
    fontSize: 13,
    color: "#374151",
  },

  daySection: {
    marginBottom: 8,
  },
  dayTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1E3A8A",
    marginBottom: 8,
  },
  stopCard: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    padding: 12,
    marginBottom: 10,
  },
  stopHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  stopTitle: { flex: 1, fontSize: 14, fontWeight: "700", color: "#111827", marginRight: 8 },
  stopMeta: { marginTop: 4, fontSize: 12, color: "#64748B" },
  stopAddress: { marginTop: 2, fontSize: 12, color: "#475569" },
  badgeDone: {
    backgroundColor: "#DCFCE7",
    color: "#166534",
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "700",
    overflow: "hidden",
  },
  row: { flexDirection: "row", gap: 8, marginTop: 10, alignItems: "center" },
  miniBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  input: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 13,
    color: "#111827",
    backgroundColor: "#FFFFFF",
  },
  inputDisabled: {
    backgroundColor: "#F8FAFC",
    color: "#64748B",
  },
  inputNotes: { marginTop: 8, minHeight: 44 },
  inputPoints: { width: 90 },
  doneBtn: {
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  doneBtnText: { color: "#1D4ED8", fontSize: 12, fontWeight: "700" },

  emptyText: { color: "#64748B", fontSize: 12 },
});

export default styles;
