import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F7",
  },
  safeArea: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  stepLabel: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1E1E1E",
    marginTop: 6,
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E5E7EB",
    marginTop: 16,
  },
  progressFill: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "#1E1E1E",
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  mapStage: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  mapSearchBar: {
    position: "absolute",
    top: 12,
    left: 20,
    right: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  mapSearchInput: {
    fontSize: 14,
    color: "#1E1E1E",
  },
  searchResults: {
    position: "absolute",
    top: 62,
    left: 20,
    right: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 8,
  },
  searchResultItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  searchResultTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  searchResultMeta: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  stopsSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  sheetFooterGap: {
    height: 120,
  },
  sheetHandle: {
    alignItems: "center",
    marginBottom: 10,
  },
  sheetHandleBar: {
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#D1D5DB",
  },
  stopsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  stopsTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  stopItem: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    backgroundColor: "#FFFFFF",
  },
  stopTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  stopActions: {
    flexDirection: "row",
    gap: 6,
  },
  stopActionButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  stopRowInput: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  stopInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: "#1E1E1E",
  },
  stopMeta: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E1E1E",
    marginBottom: 10,
  },
  inputLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: "#1E1E1E",
    backgroundColor: "#FFFFFF",
  },
  inputRow: {
    flexDirection: "row",
    gap: 12,
  },
  inputCol: {
    flex: 1,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  chipActive: {
    backgroundColor: "#1E1E1E",
    borderColor: "#1E1E1E",
  },
  chipText: {
    fontSize: 12,
    color: "#4B5563",
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#FFFFFF",
  },
  mapPreview: {
    height: 160,
    borderRadius: 16,
    backgroundColor: "#E8F4FC",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },
  mapHint: {
    marginTop: 6,
    fontSize: 12,
    color: "#6B7280",
  },
  stopRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  stopTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  stopMeta: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  addStopRow: {
    marginTop: 12,
    gap: 10,
  },
  addStopButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#1E1E1E",
  },
  addStopText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  reviewLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  reviewLabel: {
    fontSize: 12,
    color: "#6B7280",
  },
  reviewValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  footer: {
    position: "absolute",
    height: 80,
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    backgroundColor: "#F5F5F7",
    zIndex: 5,
  },
  footerScrim: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    backgroundColor: "#ffffff",
  },
  footerRow: {
    flexDirection: "row",
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#1E1E1E",
    alignItems: "center",
  },
  secondaryText: {
    color: "#1E1E1E",
    fontWeight: "600",
  },
  primaryButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "#1E1E1E",
    alignItems: "center",
  },
  primaryText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
});

export default styles;
