import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  keyboardContainer: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  stepLabel: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  title: {
    marginTop: 4,
    fontSize: 24,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "#E5E7EB",
    marginTop: 10,
  },
  progressFill: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "#1E1E1E",
  },
  stepDots: {
    marginTop: 10,
    flexDirection: "row",
    gap: 6,
  },
  stepDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#D1D5DB",
  },
  stepDotActive: {
    backgroundColor: "#1E1E1E",
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 14,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E1E1E",
    marginBottom: 10,
  },
  helperText: {
    fontSize: 13,
    color: "#6B7280",
  },
  inputLabel: {
    marginTop: 8,
    marginBottom: 6,
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
  },
  input: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
    color: "#1E1E1E",
    marginBottom: 8,
  },
  multilineInput: {
    minHeight: 88,
  },
  inputRequired: {
    borderColor: "#FCA5A5",
    backgroundColor: "#FEF2F2",
  },
  inputRow: {
    flexDirection: "row",
    gap: 10,
  },
  inputCol: {
    flex: 1,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "#FFFFFF",
  },
  chipActive: {
    backgroundColor: "#1E1E1E",
    borderColor: "#1E1E1E",
  },
  chipText: {
    fontSize: 12,
    color: "#1E1E1E",
    fontWeight: "600",
  },
  chipTextActive: {
    color: "#FFFFFF",
  },
  searchRow: {
    marginBottom: 8,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
    color: "#1E1E1E",
  },
  searchResults: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    marginBottom: 10,
    overflow: "hidden",
  },
  searchResultItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  searchResultTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  searchResultMeta: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  map: {
    height: 220,
    borderRadius: 14,
    marginTop: 4,
  },
  addStopButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#1E1E1E",
    borderRadius: 14,
    paddingVertical: 12,
    marginTop: 4,
  },
  addStopText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  timePickerButton: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 12,
    paddingVertical: 11,
    justifyContent: "center",
    marginBottom: 8,
  },
  timePickerValue: {
    fontSize: 14,
    color: "#1E1E1E",
    fontWeight: "600",
  },
  timePickerPlaceholder: {
    fontSize: 14,
    color: "#9CA3AF",
    fontWeight: "500",
  },
  stopItem: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 10,
    marginTop: 8,
    backgroundColor: "#FFFFFF",
  },
  stopHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  stopTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  stopMeta: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
    marginBottom: 8,
  },
  stopActions: {
    flexDirection: "row",
    gap: 6,
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  reviewLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  reviewLabel: {
    fontSize: 13,
    color: "#6B7280",
  },
  reviewValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  visibilityRow: {
    flexDirection: "row",
    gap: 10,
  },
  visibilityOption: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    padding: 12,
    backgroundColor: "#FFFFFF",
  },
  visibilityOptionActive: {
    backgroundColor: "#1E1E1E",
    borderColor: "#1E1E1E",
  },
  visibilityText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  visibilityTextActive: {
    color: "#FFFFFF",
  },
  visibilitySubtext: {
    marginTop: 4,
    fontSize: 12,
    color: "#6B7280",
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  footerRow: {
    flexDirection: "row",
    gap: 10,
  },
  secondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  secondaryText: {
    color: "#6B7280",
    fontWeight: "600",
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#1E1E1E",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  primaryButtonDisabled: {
    opacity: 0.5,
  },
  primaryText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  footerHint: {
    marginTop: 8,
    alignItems: "center",
    gap: 4,
  },
  errorText: {
    marginTop: 2,
    fontSize: 12,
    color: "#DC2626",
    paddingHorizontal: 2,
  },
  timePickerModalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15,23,42,0.24)",
  },
  timePickerModalOverlay: {
    flex: 1,
  },
  timePickerModalCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  timePickerModalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 6,
  },
  timePickerModalActions: {
    marginTop: 8,
    flexDirection: "row",
    gap: 8,
  },
  timeClearButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timeClearButtonText: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "700",
  },
  timePickerSecondaryButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerSecondaryText: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "700",
  },
  timePickerPrimaryButton: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: "#111827",
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerPrimaryText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
});

export default styles;
