import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fffffff2",
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 4,
    paddingBottom: 180,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginTop: 16,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  headerLeft: {
    flex: 1,
  },
  headerRightActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1E1E1E",
    lineHeight: 36,
  },
  avatarContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  inviteButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  inviteButtonDisabled: {
    backgroundColor: "#F9FAFB",
  },
  activeTripsButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: 14,
    marginBottom: 20,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#1E1E1E",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  filterButton: {
    position: "relative",
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#DBEAFE",
  },
  filterBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: "#1D4ED8",
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  filterBadgeText: {
    color: "white",
    fontSize: 10,
    fontWeight: "700",
  },
  toggleWrap: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 999,
    padding: 4,
    gap: 4,
  },
  toggleButton: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  toggleButtonActive: {
    backgroundColor: "#1E1E1E",
  },
  toggleText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  toggleTextActive: {
    color: "#FFFFFF",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginHorizontal: 20,
  },
  emptyState: {
    marginTop: 12,
    paddingHorizontal: 20,
  },
  emptyText: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 20,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#DBEAFE",
  },
  filterChipPeople: {
    backgroundColor: "#FEF9C3",
  },
  filterChipTourism: {
    backgroundColor: "#DBEAFE",
  },
  filterChipFood: {
    backgroundColor: "#FFE4E6",
  },
  filterChipDefault: {
    backgroundColor: "#FFFFFF",
  },
  filterChipActive: {
    backgroundColor: "#2563EB",
    borderColor: "#2563EB",
  },
  filterText: {
    fontSize: 11,
    fontWeight: "600",
  },
  filterTextDark: {
    color: "#111827",
  },
  filterTextMuted: {
    color: "#4B5563",
  },
  filterTextActive: {
    color: "#FFFFFF",
  },
  floatingAdd: {
    position: "absolute",
    bottom: 110,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
  },
  inviteOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(15, 23, 42, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  inviteCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 4,
  },
  inviteTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  inviteSubtitle: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 6,
  },
  inviteTripSelector: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  inviteTripPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
    maxWidth: "48%",
  },
  inviteTripPillActive: {
    backgroundColor: "#1E1E1E",
    borderColor: "#1E1E1E",
  },
  inviteTripText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  inviteTripTextActive: {
    color: "#FFFFFF",
  },
  inviteEmpty: {
    marginTop: 12,
    paddingVertical: 8,
  },
  inviteEmptyText: {
    fontSize: 12,
    color: "#6B7280",
  },
  inviteList: {
    marginTop: 16,
    gap: 12,
  },
  inviteCurrent: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  inviteCurrentTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
    marginBottom: 8,
  },
  inviteCurrentList: {
    gap: 10,
  },
  inviteCurrentItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inviteStatus: {
    fontSize: 11,
    color: "#6B7280",
  },
  inviteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inviteAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  inviteAvatarText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  inviteName: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  inviteAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  inviteActionActive: {
    backgroundColor: "#1E1E1E",
    borderColor: "#1E1E1E",
  },
  inviteActionText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  inviteActionTextActive: {
    color: "#FFFFFF",
  },
  inviteActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  inviteSecondary: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  inviteSecondaryText: {
    fontWeight: "600",
    color: "#6B7280",
  },
  invitePrimary: {
    flex: 1,
    backgroundColor: "#1E1E1E",
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  invitePrimaryText: {
    fontWeight: "600",
    color: "#FFFFFF",
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.25)",
    justifyContent: "flex-end",
  },
  sheetOverlayTap: {
    flex: 1,
  },
  sheetContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 20,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#D1D5DB",
    alignSelf: "center",
    marginBottom: 10,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  sheetSectionTitle: {
    marginTop: 16,
    marginBottom: 10,
    fontSize: 13,
    fontWeight: "700",
    color: "#4B5563",
  },
  sheetChipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sheetActionsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 20,
  },
  sheetSecondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  sheetSecondaryText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  sheetPrimaryButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#1D4ED8",
  },
  sheetPrimaryText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
});

export default styles;
