import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 160,
  },
  card: {
    backgroundColor: "#ffffffe4",
    borderRadius: 24,
    paddingBottom: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 4,
    overflow: "hidden",
    boxShadow: "0px 2px 2px rgba(0, 0, 0, 0.01)",
  },
  cover: {
    height: 150,
    backgroundColor: "#CFE2F3",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  coverCloud: {
    position: "absolute",
    backgroundColor: "#FFFFFF",
    opacity: 0.7,
    borderRadius: 999,
  },
  followButton: {
    position: "absolute",
    top: 16,
    right: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  followText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  avatarWrap: {
    marginTop: -42,
    paddingHorizontal: 20,
  },
  avatar: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: "#E5E7EB",
    borderWidth: 4,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  name: {
    marginTop: 12,
    fontSize: 22,
    fontWeight: "700",
    color: "#1E1E1E",
    paddingHorizontal: 20,
  },
  bio: {
    marginTop: 6,
    fontSize: 14,
    color: "#6B7280",
    paddingHorizontal: 20,
    lineHeight: 20,
  },
  statsRow: {
    flexDirection: "row",
    marginTop: 16,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    overflow: "hidden",
  },
  statItem: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statDivider: {
    width: 1,
    backgroundColor: "#E5E7EB",
  },
  statValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  statLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  socialsRow: {
    flexDirection: "row",
    marginTop: 14,
    marginHorizontal: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
  },
  socialItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  socialDivider: {
    width: 1,
    backgroundColor: "#E5E7EB",
  },
  section: {
    marginTop: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  sectionTabs: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 14,
    padding: 4,
    gap: 6,
  },
  sectionTab: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
  },
  sectionTabActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 1,
  },
  sectionTabText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
  },
  sectionTabTextActive: {
    color: "#1E1E1E",
  },
  sectionContent: {
    marginTop: 16,
  },
  sectionEmpty: {
    fontSize: 12,
    color: "#6B7280",
  },
  tripCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EEF0F3",
    padding: 12,
    flexDirection: "row",
    gap: 12,
  },
  tripInfo: {
    flex: 1,
  },
  tripTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  tripMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 8,
  },
  tripMeta: {
    fontSize: 12,
    color: "#6B7280",
  },
  tripDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D1D5DB",
  },
  tripChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
    gap: 6,
  },
  tripChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#FDE68A",
  },
  tripChipCity: {
    backgroundColor: "#93C5FD",
  },
  tripChipFood: {
    backgroundColor: "#FCA5A5",
  },
  tripChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  tripImage: {
    width: 86,
    height: 86,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  tripImageInner: {
    width: "100%",
    height: "100%",
  },
  badgesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  badgeItem: {
    width: "47%",
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#EEF0F3",
  },
  badgeIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#E0F2FE",
    marginBottom: 10,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  friendsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  friendItem: {
    width: "47%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EEF0F3",
    backgroundColor: "#FFFFFF",
  },
  friendAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  friendName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
    flexShrink: 1,
  },
});

export default styles;
