import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  headerBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 120,
  },
  cloud: {
    position: "absolute",
    backgroundColor: "white",
    borderRadius: 40,
  },
  dragIndicatorContainer: {
    alignItems: "center",
    paddingTop: 8,
  },
  dragIndicator: {
    width: 40,
    height: 5,
    backgroundColor: "#D1D5DB",
    borderRadius: 3,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  imageContainer: {
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  imageViewport: {
    width: "100%",
    height: 280,
    backgroundColor: "#4A7C59",
  },
  mainImage: {
    width: "100%",
    height: 280,
    backgroundColor: "#4A7C59",
    resizeMode: "cover",
  },
  mainImagePlaceholder: {
    width: "100%",
    height: 280,
    backgroundColor: "#4A7C59",
    alignItems: "center",
    justifyContent: "center",
  },
  mainImageText: {
    color: "white",
    fontSize: 16,
    marginTop: 8,
    fontWeight: "600",
  },
  addMediaButton: {
    position: "absolute",
    top: 12,
    left: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(30,30,30,0.9)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    zIndex: 2,
  },
  deleteMediaButton: {
    position: "absolute",
    top: 12,
    right: 16,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(185,28,28,0.9)",
    borderRadius: 15,
    zIndex: 2,
  },
  tripSettingsButton: {
    position: "absolute",
    top: 12,
    right: 52,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(30,30,30,0.9)",
    borderRadius: 15,
    zIndex: 2,
  },
  addMediaText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  uploadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  uploadingText: {
    marginTop: 8,
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  avatarsContainer: {
    position: "absolute",
    top: 16,
    right: 16,
    flexDirection: "row",
  },
  avatarsContainerWithActions: {
    top: 52,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "white",
  },
  avatarStacked: {
    marginLeft: -10,
  },
  avatarText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1E1E1E",
  },
  imageIndicators: {
    position: "absolute",
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  imageIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  imageIndicatorActive: {
    backgroundColor: "white",
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  tag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  tagText: {
    fontSize: 12,
    fontWeight: "600",
  },
  tagPeople: {
    backgroundColor: "#F9E547",
  },
  tagTourism: {
    backgroundColor: "#4DA3FF",
  },
  tagFood: {
    backgroundColor: "#FF7A6E",
  },
  tagDefault: {
    backgroundColor: "#E5E7EB",
  },
  tagTextDark: {
    color: "#1E1E1E",
  },
  tagTextMuted: {
    color: "#4B5563",
  },
  tripTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1E1E1E",
    marginTop: 20,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
    marginTop: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#64748B",
    marginBottom: 2,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  statValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0F172A",
  },
  visibilityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
  },
  visibilityLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
  },
  visibilityOptions: {
    flexDirection: "row",
    gap: 8,
  },
  visibilityChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#FFFFFF",
  },
  visibilityChipActive: {
    backgroundColor: "#1E1E1E",
    borderColor: "#1E1E1E",
  },
  visibilityChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  visibilityChipTextActive: {
    color: "#FFFFFF",
  },
  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 20,
  },
  descriptionContainer: {
    marginBottom: 16,
  },
  descriptionText: {
    fontSize: 15,
    lineHeight: 24,
    color: "#374151",
  },
  playInviteButton: {
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  playInviteButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  detailsSection: {
    marginBottom: 14,
    gap: 12,
  },
  detailsSubtitle: {
    marginTop: -10,
    marginBottom: 4,
    fontSize: 13,
    color: "#64748B",
  },
  detailRow: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  detailLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  detailValue: {
    fontSize: 15,
    color: "#0F172A",
    lineHeight: 22,
  },
  detailChecklistWrap: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  mapSection: {
    marginBottom: 8,
  },
  checklistItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F8FAFC",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  checklistBullet: {
    fontSize: 16,
    lineHeight: 18,
    color: "#2563EB",
    fontWeight: "700",
  },
  checklistText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: "#1F2937",
  },
  mapContainer: {
    marginBottom: 8,
  },
  mapPlaceholder: {
    height: 160,
    backgroundColor: "#E8F4FC",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    overflow: "hidden",
    position: "relative",
  },
  mapPreviewBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "rgba(30,30,30,0.72)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  mapPreviewText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  mapSubtext: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 4,
    position: "absolute",
    bottom: 10,
    left: 10,
    right: 10,
    textAlign: "center",
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 999,
    paddingVertical: 4,
  },
  floatingBar: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    flexDirection: "row",
    backgroundColor: "#1E1E1E",
    borderRadius: 32,
    paddingVertical: 8,
    paddingHorizontal: 14,
    gap: 14,
  },
  actionItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 44,
  },
  actionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  actionCopy: {
    backgroundColor: "#C8F06A",
  },
  actionLike: {
    backgroundColor: "#FF6B6B",
  },
  actionLikeActive: {
    backgroundColor: "#EF4444",
  },
  actionAsk: {
    backgroundColor: "#FFFFFF",
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1E1E1E",
    marginBottom: 16,
  },
  itinerarySection: {
    backgroundColor: "#FCFCFD",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    padding: 12,
  },
  itineraryItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  itineraryContent: {
    flex: 1,
  },
  dayBadge: {
    backgroundColor: "#DFF8AE",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginRight: 12,
  },
  dayText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  itineraryText: {
    fontSize: 15,
    color: "#374151",
  },
  itineraryTime: {
    marginTop: 4,
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "600",
  },
  pdfSection: {
    marginBottom: 10,
    gap: 10,
    backgroundColor: "#FCFCFD",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    padding: 12,
  },
  pdfHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  pdfSectionTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1E1E1E",
    marginBottom: 0,
    flexShrink: 1,
    paddingRight: 8,
  },
  pdfUploadButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#111827",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  pdfUploadButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  pdfEmptyText: {
    fontSize: 14,
    color: "#6B7280",
  },
  pdfCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    padding: 12,
    gap: 10,
  },
  pdfMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pdfMetaTextWrap: {
    flex: 1,
  },
  pdfTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  pdfSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: "#6B7280",
  },
  pdfActions: {
    flexDirection: "row",
    gap: 8,
  },
  pdfDownloadButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  pdfDownloadText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1F2937",
  },
  pdfDeleteButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "#B91C1C",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  pdfDeleteText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  bottomSpacer: {
    height: 110,
  },
  tripSettingsBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.28)",
    justifyContent: "flex-end",
  },
  tripSettingsOverlayTap: {
    flex: 1,
  },
  tripSettingsSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 24,
    gap: 10,
  },
  tripSettingsTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
  },
  tripSettingsDangerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 12,
    backgroundColor: "#B91C1C",
    paddingVertical: 12,
  },
  tripSettingsDangerButtonDisabled: {
    opacity: 0.55,
  },
  tripSettingsDangerText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  tripSettingsCancelButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  tripSettingsCancelText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  commentsBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.28)",
    justifyContent: "flex-end",
  },
  commentsOverlayTap: {
    flex: 1,
  },
  commentsKeyboardWrap: {
    justifyContent: "flex-end",
  },
  commentsSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 20,
    minHeight: 360,
    maxHeight: "78%",
  },
  commentsHandle: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#D1D5DB",
    alignSelf: "center",
    marginBottom: 10,
  },
  commentsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 12,
  },
  replyBanner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
  },
  replyBannerText: {
    color: "#1E40AF",
    fontSize: 12,
    fontWeight: "600",
  },
  replyBannerCancel: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "700",
  },
  commentsLoading: {
    paddingVertical: 20,
  },
  commentsEmptyText: {
    color: "#6B7280",
    fontSize: 14,
    paddingVertical: 20,
  },
  commentsList: {
    flexGrow: 0,
  },
  commentsListContent: {
    paddingBottom: 8,
    gap: 10,
  },
  commentThread: {
    gap: 8,
  },
  commentCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  commentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  commentActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  commentAuthor: {
    fontSize: 13,
    color: "#1F2937",
    fontWeight: "700",
  },
  commentReply: {
    fontSize: 12,
    color: "#1D4ED8",
    fontWeight: "600",
  },
  commentDelete: {
    fontSize: 12,
    color: "#B91C1C",
    fontWeight: "600",
  },
  replyCard: {
    marginLeft: 18,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  commentBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "#374151",
  },
  commentComposer: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  commentInput: {
    flex: 1,
    minHeight: 42,
    maxHeight: 110,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    color: "#111827",
  },
  commentSendButton: {
    backgroundColor: "#111827",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  commentSendButtonDisabled: {
    backgroundColor: "#9CA3AF",
  },
  commentSendText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
});

export default styles;
